Update __init__.py
Because

File "/home/djaler/Projects/Python/TranslationBot/venv/lib/python3.5/site-packages/sqlite3worker/__init__.py", line 28, in <module>
    from sqlite3worker import Sqlite3Worker
ImportError: cannot import name 'Sqlite3Worker'